name: Release Workflow

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: Release Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Repository Checkout 🛎
        uses: actions/checkout@v4.1.7

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Registry Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker 🗞
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Set up Docker Buildx 💊
        id: buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Build & Push Docker Image 📦
        id: docker_build
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  notification:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.7

      - name: Discord notification
        uses: bythope/discord-webhook-messages@v1.1.0
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          handler: 'release'
